### ISSUE TITLE
add a view daily diffs

### ISSUE THREAD

**Issue by muescha** [maxMaxineChen/COVID19-Worldwide-Stats#1]
please add also a daily diff

- worldwide
- also per country

i miss this per country in most maps :(
with this diff i hope it is visible if the #stayathome works in a country

PS:
here there is it in the lower right box:
https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

<img width="399" alt="Bildschirmfoto 2020-03-23 um 17 02 36" src="https://user-images.githubusercontent.com/184316/77336662-224fdc80-6d28-11ea-9f23-506dc2787ba5.png">

**Comment by maxMaxineChen** [comment]
Thank you @muescha. I'll add daily diff later on. In terms of the impact of #stayathome, that's an interesting idea. But I have to do some research to see how to get meaningful data. Please let me know if you have any idea :-)

**Comment by muescha** [comment]
sorry i don't have an idea where to get the data

**Comment by maxMaxineChen** [comment]
Hi, @muescha I've added growth and growth rate to the project. But I haven't found a good way to do the diff visualization of #stayathome yet.
It may be a someday feature so that I close the issue now.
Feel free to commit any issues or ideas.
