### ISSUE TITLE
Order COVID-19 Cases Worldwide by amount desc

### ISSUE THREAD

**Issue by muescha** [maxMaxineChen/COVID19-Worldwide-Stats#2]
where:

- graph "COVID-19 Cases Worldwide"

what i see:

- since the values are not sortet countries with few cases are mixed with countries with many cases and then the graph is not that detailed, because the graph is depending on max cases by the visible countries

what i expect:
- order by cases desc
- countries with less cases are better visible

**Comment by maxMaxineChen** [comment]
The feature has been implemented. Thanks.

**Comment by muescha** [comment]
👍
